# Generated by Django 3.2.4 on 2021-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210604_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workfeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='Workfeatured_file')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Workfeatured',
                'verbose_name_plural': 'Workfeatureds',
            },
        ),
    ]
